### ISSUE TITLE
Bot failed to send chat

### ISSUE THREAD

**Issue by AnakTeka** [franciscod/telegram-twitter-forwarder-bot#12]
From log ` TwitterForwarderBot - INFO - Couldn't send tweet 767299741981954050 to chat 130145717: 'Bad Request: Url host is empty'`

Any idea why this is happening? Used to work fine :/

**Comment by franciscod** [comment]
Huh? Never seen that before... Maybe the tweet was deleted really fast and
tweepy fails to fetch it? Try to repro in a minimal sqlite database :)
