### ISSUE TITLE
[Proposal] Add #hashtags in sub command

### ISSUE THREAD

**Issue by amallia** [franciscod/telegram-twitter-forwarder-bot#21]
What about adding hashtags in the sub command, so people can subscribe for updates coming from any author on a specific topic?
Command would change in `Use /sub @username1 @username2 #hashtag1 #hashtag2... `
Based on the first character the command will create two distinct lists containing usernames and hashtags to follow.

**Comment by krikunts** [comment]
I doubt we should implement this. The amount of tweets for just one hashtag can be *huge*. If everyone will be able to subscribe to hashtags overall performance will decrease *a lot*.

**Comment by franciscod** [comment]
Agree, hashtags can get quite traffic-y

**Comment by Kiku-git** [comment]
And if you do not directly send data from hashtags to a direct line? Set limits. Process on the server. And do not make global hashtags, but only with selected accounts.

**Comment by franciscod** [comment]
I'm happy to review PRs implementing this, but I'm still skeptic about it working well.
