### ISSUE TITLE
Post full tweet to Telegram 

### ISSUE THREAD

**Issue by MohammedHoosen** [franciscod/telegram-twitter-forwarder-bot#24]
Now that Twitter has increased the amount of characters in a tweet will it be possible to post the full tweet text to telegram without the url linking to the extended text.

**Comment by johnmee** [comment]
[See the Pull Request from krikunts](https://github.com/franciscod/telegram-twitter-forwarder-bot/pull/20/commits/5162a377d563239c98c5b74b240584a870264fef
)

**Comment by franciscod** [comment]
Merged! Thanks!
