### ISSUE TITLE
Rename bot?

### ISSUE THREAD

**Issue by Swiftnesses** [franciscod/telegram-twitter-forwarder-bot#33]
Hello,

Fantastic bot! We'd love to rename it to "Our Channel Name - Tweets", can we somehow rename the bot?

**Comment by Adem1987** [comment]
You could host your own one and change the name how you like it.

**Comment by Swiftnesses** [comment]
That's the plan, is the change easy?

**Comment by Adem1987** [comment]
Yes. Make a Bot with @Botfather. Host the Bot somewhere and use the token from Botfather in your copied code.

**Comment by Adem1987** [comment]
You can also give a name in Botfather.

**Comment by franciscod** [comment]
@Adem1987 gets a medal! Thanks!
