### ISSUE TITLE
Posting in Telegram Channel

### ISSUE THREAD

**Issue by fabston** [franciscod/telegram-twitter-forwarder-bot#40]
Is there a solution so that the bot is able to post in channels? As long as the bot cant read messages so /sub is redundant?

**Comment by fabston** [comment]
was able to fix it myself!

**Comment by franciscod** [comment]
how did you solve it? :)

**Comment by SHi-ON** [comment]
Would you mind to explain the way to make the bot post to channels?
@franciscod
