### ISSUE TITLE
Sourcing secrets.env doesn't work smoothly on Windows

### ISSUE THREAD

**Issue by shanghei** [franciscod/telegram-twitter-forwarder-bot#47]
Keep getting the following error 

C:\Users\user\Downloads\telegram-twitter-forwarder-bot-master\telegram-twitter-forwarder-bot-master>main.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\telegram-twitter-forwarder-bot-master\telegram-twitter-forwarder-bot-master\main.py", line 32, in <module>
    auth = tweepy.OAuthHandler(env('TWITTER_CONSUMER_KEY'), env('TWITTER_CONSUMER_SECRET'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\envparse.py", line 107, in __call__
    return env(var, cast=cast, default=default)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\envparse.py", line 39, in env
    value = os.environ[var]
  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'TWITTER_CONSUMER_KEY'

thank you

**Comment by Adem1987** [comment]
You have to add your twitter data. Just search for it.

**Comment by shanghei** [comment]
> You have to add your twitter data. Just search for it.

I added my Twitter consumer key and consumer secret and also my access token and access token secret.

**Comment by franciscod** [comment]
from the readme:

Get a consumer key, consumer secret, access token and access token secret (the latter two are optional), fill in your secrets.env, source it, and then run the bot!

The error message could be a bit clearer, though...

**Comment by shanghei** [comment]
Ive done all that, I put my twitter data in the secrets.env 
![twit1](https://user-images.githubusercontent.com/55709707/85908839-d60faf00-b7e4-11ea-9b8f-a83e0e681c88.jpg)
![twit2](https://user-images.githubusercontent.com/55709707/85908840-d6a84580-b7e4-11ea-828a-4ba316a39760.jpg)

**Comment by franciscod** [comment]
did you source the file before running python? (add the variables to your environment)

**Comment by shanghei** [comment]
> did you source the file before running python? (add the variables to your environment)

That's most likely the step I'm missing, not sure how to source in Windows

**Comment by franciscod** [comment]
You can try adding something like this around line 30 of main:

```python
env.read_envfile('secrets.env')```

**Comment by franciscod** [comment]
Now the configuration is a bit simpler, with a `secrets.env` written in python, no environment variables. Check it out!
