### ISSUE TITLE
Bot not read messages in channel

### ISSUE THREAD

**Issue by damianetienne** [franciscod/telegram-twitter-forwarder-bot#48]
Hello

I've worked with the bot and worked like a charm on groups, but i can't make work on my public channel.

I've added my telegram bot to the target channel (as admin), but at the time to send my command, the bot did't reply and the action doesn't show on the terminal ( as "Getting updates")

There is any step that i've have ommited?

Thanks in advance

**Comment by Adem1987** [comment]
Try this:
Open the database. Enter your channel id and add manually all subscriptions.

**Comment by damianetienne** [comment]
Thanks for the answer

Yes, i did that. Isn't a beautiful solution, but it works.

**Comment by franciscod** [comment]
Thanks @Adem1987 for helping out!

**Comment by ACHIYA96** [comment]
Are there any other solutions? (Without manually editing the database?) Thanks.

**Comment by franciscod** [comment]
not right now. but a command could be added like /subchannel <telegramchannel> <twitterhandle>
