### ISSUE TITLE
What am I doing wrong when filling secrets.py?

### ISSUE THREAD

**Issue by SuperPerro95** [franciscod/telegram-twitter-forwarder-bot#52]
Well, I ONLY FILLED THE INFO IN SECRETS.PY how come it is missing if its there. What am i doing wrong?

![image](https://user-images.githubusercontent.com/79465829/108748727-aeace580-751d-11eb-8210-6349ad009112.png)

**Comment by franciscod** [comment]
You probably want to uncomment those lines. Remove the leading `#`.

**Comment by SuperPerro95** [comment]
> You probably want to uncomment those lines. Remove the leading `#`.

Oh so that's what uncomment means. And where should I write the twitter username I want to post in telegram?
