### ISSUE TITLE
Sending media

### ISSUE THREAD

**Issue by rijeshkumar** [franciscod/telegram-twitter-forwarder-bot#62]
It will be better if there is any media in tweet bot should send it with text message in that tweet as a caption of the media. Now images in tweets are sending as preview only

**Comment by franciscod** [comment]
This would need the bot to download the media to forward it as well. I don't think that's a thing to take lightly.. but if someone out there wants to implement this as a configurable behaviour, I'd accept a PR :)

**Comment by rijeshkumar** [comment]
Where I should make change if I don't need time of the tweet in the message

**Comment by rijeshkumar** [comment]
Losing all the subscription in random time interval. I have to add subscription again and again each day. I deployed bot in heroku. How to avoid this issue?

**Comment by franciscod** [comment]
I don't know. 
Please let's discuss this on a different issue. But here's a start that you can quote:
Have you checked your database? 
Are you losing rows in the tables?
Where is the database stored?

**Comment by rijeshkumar** [comment]
I don't know where database is storing. I don't know what changes happening in it. I deployed bot in heroku. Within 24 hours I losing all subscriptions and have to subscribe them again.

**Comment by franciscod** [comment]
**Please let's discuss this on a different issue.**
