### ISSUE TITLE
Losing all subscription within 24 hours when deployed in heroku

### ISSUE THREAD

**Issue by rijeshkumar** [franciscod/telegram-twitter-forwarder-bot#65]
I deployed bot in heroku. Problem is I losing all the subscription within 24 hours and I have to subscribe each of them again and again each day. Feeds stoping before 24 hours and when I check the /list it showing nothing subscribed

**Comment by franciscod** [comment]
Where is the database stored?

My guess would be that Heroku is probably giving you a fresh "dyno" periodically, which wipes out the files created at runtime.

**Comment by rijeshkumar** [comment]
I don't know where heroku storing database. I created a database add on. And waiting for a result.

**Comment by rijeshkumar** [comment]
I got the reason behind it. In there is dyno recycling. All your dynos will be restarted within 24hours+ 216 random minutes. We can't avoid this recycling also. So is there any way to avoid losing all subscriptions?

**Comment by franciscod** [comment]
Yes, use a database that won't get recycled.

Heroku provides a few DB services (e.g. PostgreSQL).
peewee (our DB layer) supports PostgreSQL and MySQL as well.

You could also do some kind of network mount to some external server and keep the sqlite DB synced there but that seems to be more trouble than it's worth.

**Comment by rijeshkumar** [comment]
I created a database in heroku but I don't know how to connect that with bot. Can u help in it?
