### ISSUE TITLE
How to use it in Telegram Channel/Group

### ISSUE THREAD

**Issue by feramuzerd** [franciscod/telegram-twitter-forwarder-bot#69]
I am a rookie, an undergraduate student, and want to follow researchers, academicians, labs, universities, latest news from research etc in telegram because social media distracts me, even I have ADHD. Bot works on a Droplet, but not in Telegram, I couldn't. How can I add bot to my telegram group or channel?

it is done

**Comment by franciscod** [comment]
Welcome!

What do you mean by "works on a Droplet but not in Telegram"?

**Comment by topalasker** [comment]
to make it online everytime.

**Comment by topalasker** [comment]
oww it already works. Sorry for misunderstanding.
