### ISSUE TITLE
would you please help me on installing the bot on an EC2?

### ISSUE THREAD

**Issue by lzuxz** [franciscod/telegram-twitter-forwarder-bot#7]
Thank you very much for your code!
when i install it in an ubuntu@EC2 following the instruction, I got this error, Would you like to read it and give me some suggetion. Thank you!

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot import TwitterForwarderBot, FetchAndSendTweetsJob
  File "/home/ubuntu/telegram-twitter-forwarder-bot/bot.py", line 9, in <module>
    from basebot import BaseBot, Job
  File "/home/ubuntu/telegram-twitter-forwarder-bot/basebot.py", line 98
    command, *args = text[1:].split()
             ^
SyntaxError: invalid syntax
```

**Comment by lzuxz** [comment]
ok I got the point.
the environment is not setup correctly.
Thank you anyway.

**Comment by franciscod** [comment]
Yeah, that syntax is new on py3. How did you solve it in your specific case on EC2?

**Comment by lzuxz** [comment]
```
# clone this thing
# create your virtualenv, activate it, etc
# virtualenv -p python3 venv
# . venv/bin/activate
pip install -r requirements.txt
source secrets.env
python main.py
```
uncomment these two lines would work
```
 virtualenv -p python3 venv
 . venv/bin/activate
```
Thank you!

**Comment by franciscod** [comment]
Oh yes, they are commented because there are other ways to do virtualenv
like using venvwrapper, workon and other tools. Probably this should be
noted in the readme, though :p

**Comment by franciscod** [comment]
Closing this guy!
